baseURL = "https://example.com/"
languageCode = "en-US"
title = "Omar Elmasri"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profilepic.png"
  author = "Omar Elmasri"
  description = "My portfolio"


[params.social]
  Github        = "masriomarm"
  Email         = "masri.omarm@gmail.com"
  Twitter       = "masriomarm"
  LinkedIn      = "masriomarm"
#  Stackoverflow = "masriomarm"
#  Medium        = "masriomarm"
  Telegram      = "masriomarm"
#  RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/docs/resume-omar-mahmoud.pdf"
